require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BookFragmentsController do

  def mock_book_fragment(stubs={})
    @mock_book_fragment ||= mock_model(BookFragment, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all book_fragments as @book_fragments" do
      BookFragment.stub(:all) { [mock_book_fragment] }
      get :index
      assigns(:book_fragments).should eq([mock_book_fragment])
    end
  end

  describe "GET show" do
    it "assigns the requested book_fragment as @book_fragment" do
      BookFragment.stub(:find).with("37") { mock_book_fragment }
      get :show, :id => "37"
      assigns(:book_fragment).should be(mock_book_fragment)
    end
  end

  describe "GET new" do
    it "assigns a new book_fragment as @book_fragment" do
      BookFragment.stub(:new) { mock_book_fragment }
      get :new
      assigns(:book_fragment).should be(mock_book_fragment)
    end
  end

  describe "GET edit" do
    it "assigns the requested book_fragment as @book_fragment" do
      BookFragment.stub(:find).with("37") { mock_book_fragment }
      get :edit, :id => "37"
      assigns(:book_fragment).should be(mock_book_fragment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created book_fragment as @book_fragment" do
        BookFragment.stub(:new).with({'these' => 'params'}) { mock_book_fragment(:save => true) }
        post :create, :book_fragment => {'these' => 'params'}
        assigns(:book_fragment).should be(mock_book_fragment)
      end

      it "redirects to the created book_fragment" do
        BookFragment.stub(:new) { mock_book_fragment(:save => true) }
        post :create, :book_fragment => {}
        response.should redirect_to(book_fragment_url(mock_book_fragment))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved book_fragment as @book_fragment" do
        BookFragment.stub(:new).with({'these' => 'params'}) { mock_book_fragment(:save => false) }
        post :create, :book_fragment => {'these' => 'params'}
        assigns(:book_fragment).should be(mock_book_fragment)
      end

      it "re-renders the 'new' template" do
        BookFragment.stub(:new) { mock_book_fragment(:save => false) }
        post :create, :book_fragment => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested book_fragment" do
        BookFragment.stub(:find).with("37") { mock_book_fragment }
        mock_book_fragment.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :book_fragment => {'these' => 'params'}
      end

      it "assigns the requested book_fragment as @book_fragment" do
        BookFragment.stub(:find) { mock_book_fragment(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:book_fragment).should be(mock_book_fragment)
      end

      it "redirects to the book_fragment" do
        BookFragment.stub(:find) { mock_book_fragment(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(book_fragment_url(mock_book_fragment))
      end
    end

    describe "with invalid params" do
      it "assigns the book_fragment as @book_fragment" do
        BookFragment.stub(:find) { mock_book_fragment(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:book_fragment).should be(mock_book_fragment)
      end

      it "re-renders the 'edit' template" do
        BookFragment.stub(:find) { mock_book_fragment(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested book_fragment" do
      BookFragment.stub(:find).with("37") { mock_book_fragment }
      mock_book_fragment.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the book_fragments list" do
      BookFragment.stub(:find) { mock_book_fragment }
      delete :destroy, :id => "1"
      response.should redirect_to(book_fragments_url)
    end
  end

end
